CXX_EXTRA_FLAGS=-I ../external/lazycsv/include -I ../external/eigen
TIDY_EXTRA_FLAGS=-I .

include ../Makefile.inc

release : gauss

gauss  : util.r.o Gauss_main.r.o Gauss_solve.r.o
	$(LD) -o $@ $^

debug   : util.d.o Gauss_main.d.o Gauss_solve.d.o
	$(LD) -o $@ $^

utest   : Gauss_test.d.o util.d.o Gauss_solve.d.o
	$(LD) -o $@ $^ $(GTEST_LIBS)

run_utest : utest
	./$^

run_itest : release
	echo "Integration tests..."
	./integration_test.sh

all: depends run_utest run_itest

include Makefile.hdrdep
